---
title: "Affect and SM Use - SMASH Study"
author: "Melissa Dreier"
date: "10/31/2023"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loaddata, include=FALSE}

#library(readr)
setwd("C:/Users/Missy Dreier/Box/The Hamilton Lab/Studies- Complete or Collabs/SMASH Study/Data for Analysis")
data <- read.csv("final_SMASH_data_clean.csv") # main dataset


```

```{r setrparams, include=FALSE}

r = getOption("repos")
r["CRAN"] = "http://cran.us.r-project.org"
options(repos = r)

.libPaths("C:/Users/Missy Dreier/Documents") # ensure packages install in the correct place
set.seed(1229)

```

```{r loadpackages, include=FALSE}
# write function that installs and reads packages in reproducible format
read_functions <- function (pkg) {
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE)
}

# make list of packages used
packages <- c("lme4","lmerTest", "nlme", "tidyverse", "Hmisc", "brms","ggplot2", "sjstats","sjPlot","bayesplot", "coda", "EMAtools", "parameters", "naniar")

# apply function to read in above packages
read_functions(packages)

```


```{r datacleaning, include=FALSE}

## remove rows where "hour in study" = NA. This means this was outside of the passive monitoring period
data <- data[-which(is.na(data$hour_in_study)),]


## remove anyone who does not have SM data (in our study, these are iPhone users or people whose passive monitoring app did not work during the study period)
data <- data %>%
  filter(Any_SM == 1)




## get info about missing data


## summarize data by day

day <- data %>%
  group_by(pid, day_in_study) %>%
  dplyr::summarise(sum_sm = sum(phone_applications_foreground_rapids_sumdurationsm_sns_community_video_sns, na.rm = TRUE), NAf_am = mean(Mood_1_am, na.rm=TRUE), NAf_pm = mean(Mood_1_pm, na.rm=TRUE), count_sm = sum(phone_applications_foreground_rapids_counteventsm_sns_community_video_sns, na.rm = TRUE), SM_Pos = mean(SMPos_1_pm, na.rm=TRUE), SM_Neg = mean(SMNeg_1_pm, na.rm=TRUE)) %>%
  mutate(NAf_sum = NAf_am + NAf_pm)

## add between-person variables (i.e., average of vars of interest for each participant, rather than participant by day)
day <- day %>%
  group_by(pid) %>%
  mutate(sm_average = mean(sum_sm, na.rm=TRUE), PA_sm_average = mean(SM_Pos, na.rm=TRUE), NA_sm_average = mean(SM_Neg, na.rm=TRUE), count_average = mean(count_sm, na.rm=TRUE))



#set weakly informative gaussian prior####
prior1 <- c(brms::set_prior("normal(0, 10)", class = "b"),
            brms::set_prior("normal(0, 10)", class = "Intercept")
)


## person-centered means


day$sum_sm_p_c <- pmean(day$pid, day$sum_sm) # Sum SM overall person-centered mean
day$sum_sm_p <- (day$sum_sm - day$sum_sm_p_c) # Sum SM daily person-centered var


day$count_sm_p_c <- pmean(day$pid, day$count_sm) # Count SM overall person-centered mean
day$count_sm_p <- (day$count_sm - day$count_sm_p_c) # Count SM daily person-centered var

day$SM_Pos_p_c <- pmean(day$pid, day$SM_Pos) # SM Positive Affect overall person-centered mean
day$SM_Pos_p <- (day$SM_Pos - day$SM_Pos_p_c) # SM Positive Affect daily person-centered var


day$SM_Neg_p_c <- pmean(day$pid, day$SM_Neg) # SM Negative Affect overall person-centered mean
day$SM_Neg_p <- (day$SM_Neg - day$SM_Neg_p_c) # SM Negative Affect daily person-centered var


day$NAf_am_p_c <- pmean(day$pid, day$NAf_am) # Morning negative affect overall mean
day$NAf_am_p <- (day$NAf_am - day$NAf_am_p_c) # Morning negative Affect daily person-centered var

day$NAf_pm_p_c <- pmean(day$pid, day$NAf_pm) # Evening negative affect overall mean
day$NAf_pm_p <- (day$NAf_pm - day$NAf_pm_p_c) # Evening negative Affect daily person-centered var


day$NAf_p_c <- pmean(day$pid, day$NAf_sum) # Evening negative affect overall mean
day$NAf_p <- (day$NAf_sum - day$NAf_pm_p_c) # Evening negative Affect daily person-centered var


### lagged variables


day <- day %>% group_by(pid) %>%
  dplyr::mutate(sum_sm_p_lag = lag(sum_sm_p, n = 1, default = NA), count_sm_p_lag = lag(count_sm_p, n = 1, default = NA), NAf_am_p_lag = lag(NAf_am_p, n = 1, default = NA), NAf_pm_p_lag = lag(NAf_pm_p, n = 1, default = NA), SM_Pos_p_lag = lag(SM_Pos_p, n = 1, default = NA), SM_Neg_p_lag = lag(SM_Neg_p, n = 1, default = NA), NAf_p_lag = lag(NAf_p, n = 1, default = NA))


```

# Descriptive Statistics

```{r descriptives, include=TRUE, message=FALSE, warning = FALSE}



## Days in Study

# summarize max days in study
Max_days <- data %>%
  group_by(pid) %>%
  summarise(Max_day = max(day_in_study, na.rm=TRUE))

# get mean/sd day in study
mean(Max_days$Max_day, na.rm=TRUE)
sd(Max_days$Max_day, na.rm=TRUE)

#min(Max_days$Max_day, na.rm=TRUE)

#View(Max_days)

#setwd("C:/Users/Missy Dreier/OneDrive - Rutgers University/Documents/Papers/2022_SMASH_Affect/Paper writing/Current Research in Ecological and Social Psychology/RR1")

#getwd()

#write.csv(Max_days, file = "Days_in_study.csv", row.names = F)


wide <- data[which(data$day_in_study==1 & data$hour_in_study==1),] # create dataset with 1 row/participant for demographics

gender <- wide %>% select("pid", "GenderBirth") # subset data to just ID and sex

totals <- day %>% group_by(pid) %>%
  dplyr::summarise(sum_sm = sum(sum_sm, na.rm = TRUE), NAf_am = mean(NAf_am, na.rm=TRUE), NAf_pm = mean(NAf_pm, na.rm=TRUE), count_sm = sum(count_sm, na.rm = TRUE), SM_Pos = mean(SM_Pos, na.rm=TRUE), SM_Neg = mean(SM_Neg, na.rm=TRUE))

## summarize dataset

daygen <- merge(totals, gender, by = "pid") #merge


t.test(sum_sm ~ GenderBirth, data = daygen) #test sex differences in SM screen time

t.test(count_sm ~ GenderBirth, data = daygen) #test sex diffs in SM checking


t.test(SM_Pos ~ GenderBirth, data = daygen) #test sex diffs in positive affect SM


t.test(SM_Neg ~ GenderBirth, data = daygen) #test sex diffs in negative affect SM


t.test(NAf_am ~ GenderBirth, data = daygen) #test sex diffs in general negative affect AM


t.test(NAf_pm ~ GenderBirth, data = daygen) #test sex diffs in general negative affect PM

```



# Models Prediciting Next morning Negative Mood 
```{r, message=FALSE, warning=FALSE, include=TRUE}


#---------------------------------------------Bayesian multilevel models---------------------------------------#

## Negative mood - sumduration
NA_sm_sum_bayes  <- brm(NAf_am_p ~ sum_sm_p_lag + sum_sm_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(NA_sm_sum_bayes, centrality = "mean")
standard_error(NA_sm_sum_bayes)


## Negative mood - counts

NA_sm_count_bayes  <- brm(NAf_am_p ~ count_sm_p_lag + count_sm_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(NA_sm_count_bayes, centrality = "mean")
standard_error(NA_sm_count_bayes)





```





## Positive Affect on SM predicting social media use
```{r, include=TRUE, message=FALSE, warning=FALSE}

#--------------------------------------------Bayesian multilevel models-------------------------------------------#

## Positive affect & minutes of SM

PA_on_SM_day_bayes  <- brm(sum_sm_p ~ SM_Pos_p_lag + SM_Pos_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(PA_on_SM_day_bayes, centrality = "mean")
standard_error(PA_on_SM_day_bayes)



## Minutes of SM --> positive mood


SM_on_PA_day_bayes  <- brm(SM_Pos_p ~ sum_sm_p_lag + sum_sm_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(SM_on_PA_day_bayes, centrality = "mean")
standard_error(SM_on_PA_day_bayes)



## Positive affect & SM checks

PA_on_SM_count_day_bayes  <- brm(count_sm_p ~ SM_Pos_p_lag + SM_Pos_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(PA_on_SM_count_day_bayes, centrality = "mean")
standard_error(PA_on_SM_count_day_bayes)


## SM Checks --> positive mood


SM_count_on_PA_day_bayes  <- brm(SM_Pos_p ~ count_sm_p_lag + count_sm_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(SM_count_on_PA_day_bayes, centrality = "mean")
standard_error(SM_count_on_PA_day_bayes)
 

```

## Negative Affect on SM predicting social media use
```{r, include=TRUE, message=FALSE, warning=FALSE}


#---------------------------------------------Bayesian multilevel models---------------------------------------#


## Negative affect & minutes of SM

NA_on_SM_day_bayes  <- brm(sum_sm_p ~ SM_Neg_p_lag + SM_Neg_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(NA_on_SM_day_bayes, centrality = "mean")
standard_error(NA_on_SM_day_bayes)


## Minutes of SM --> NA

SM_on_NA_day_bayes  <- brm(SM_Neg_p ~ sum_sm_p_lag + sum_sm_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(SM_on_NA_day_bayes, centrality = "mean")
standard_error(SM_on_NA_day_bayes)


## Negative affect & SM checks

NA_on_SM_count_day_bayes  <- brm(count_sm_p ~ SM_Neg_p_lag + SM_Neg_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(NA_on_SM_count_day_bayes, centrality = "mean")
standard_error(NA_on_SM_count_day_bayes)


## SM Checks --> NA

SM_count_on_NA_day_bayes  <- brm(SM_Neg_p ~ count_sm_p_lag + count_sm_p_c + day_in_study + (1 | pid), prior = prior1, data = day)

model_parameters(SM_count_on_NA_day_bayes, centrality = "mean")
standard_error(SM_count_on_NA_day_bayes)




```







